2196242 bosh documentation
anynines/docs-a9s-bosh pull request #2
Opened 2017-09-05 09:40 UTC by gogolok

2017-09-05 15:26 UTC, lucaspinto requested changes
Let's talk about this together and see how we can rewrite some of those.

2017-09-05 15:26 UTC, lucaspinto commented on docs-content/usecase.html.md.erb
> +In general, it is expected to have only a few tiles in your <b>PCF Ops Manager Director</b>,
Not a huge fan of the "this is expected" formulation. What do you mean here? Are you describing a typical use case?

2017-09-05 15:26 UTC, lucaspinto commented on docs-content/usecase.html.md.erb
> +* __Configuration:__ the <b>Ops Manager</b> might not provide a configuration
The way to paragraph is written is quite confusing. It feels that this needs to be cut in at least 2 sentences. It also has grammar mistakes :)

2017-09-05 15:26 UTC, lucaspinto commented on docs-content/usecase.html.md.erb
> +* Etc.
Say that the list is not exhaustive if needed, but avoid "Etc." in bullet points.

2017-09-05 15:26 UTC, lucaspinto commented on docs-content/usecase.html.md.erb
> +* Etc.
It is possible to have "Etc." ? :)

2017-09-13 12:00 UTC, phartz commented
close pull against our master branch
I updated the repo with the upstream and will merge into a new feature, which we can use to create our PR against the forked repo from pivotal

2017-09-13 12:00 UTC, closed without merging